name: call-app
services:
  - name: web
    type: web
    env:
      - name: PORT
        value: "8080"
    ports:
      - port: 8080
        protocol: http
    routes:
      - path: /
        public: true
    build:
      type: node
      version: 16
    command: npm start